### ISSUE TITLE
This won’t load on my iPad

### ISSUE THREAD

**Issue by TheRogue12** [Randomblock1/unblock-survivio#3]
Hey whenever I try to load the Surviv.io link on my iPad the page will load but the game isn’t there. The attachment shows what it looks like. Thanks for your time. 
![fabe9106-156d-4032-808c-edaed79e99a3](https://user-images.githubusercontent.com/45881539/50017437-e48ad280-ff80-11e8-8b01-dd04805d1c83.png)

EDIT: It’s not your design that would not let Surviv load. It won’t load because SFUSD’s webfilter is really good. If you could make this so that the SFUSD webfilter does not block it that would be amazing. Thanks.

**Comment by Randomblock1** [comment]
I wasn’t able to reproduce this bug on my iPhone. If you have a content blocker on, try turning it off via Safari Settings.
It looks like you’re using a VPN. That’s great, but it might interfere with the webpage. Try using it with that turned off.
However, it could be a problem with surviv.io. Try visiting surviv.io on a non-restricted connection, and tell me if that works.

**Comment by Randomblock1** [comment]
Unfortuantely, your school uses a different kind of filter that will not be bypassed by this tool. Instead of blocking direct access to the site but ignoring iframes like Securly, it blocks any traffic sent to those servers. I may be able to help though, with proxy sites. 
Also, when you edit your comments, I don't get notified of them, which is why I'm 20 days late. Please make a new comment instead of editing your old one, it helps a lot. Thanks.

**Comment by Randomblock1** [comment]
You can try to use Glype web proxies, and those might work to unblock websites. Here's the one I use: https://tonernews.com/glype/
Go to options and enable scripts and every site should work normally.
