### ISSUE TITLE
Same issue as the other guy

### ISSUE THREAD

**Issue by chargedpika** [Randomblock1/unblock-survivio#6]
I have securely, but for some reason the iframe won’t load. It’s stuck on that picture that you said you can’t reproduce. No VPN, no anything

**Comment by Randomblock1** [comment]
I’m sorry, I don’t know how to fix it. I don’t have an iPad and I don’t see anything wrong in the code. You’re welcome to make a fork and try to fix it. If you manage to fix it, make a pull request. I wish I could help, but I can’t. This seems to be an iPad specific issue, since iPhones and desktop computers load it just fine.
